# GET root URL
GET http://localhost:8000/
Accept: text/plain

###

# GET health check
GET http://localhost:8000/health
Accept: application/json

###

# GET all messages
GET http://localhost:8000/messages
Accept: application/json

###

# GET a specific message by ID
GET http://localhost:8000/messages/1
Accept: application/json

###

# POST create a new message
POST http://localhost:8000/messages
Content-Type: application/json

{
  "user": "Stephy",
  "content": "Podaaaaa!"
}

###

# PUT update a message by ID
PUT http://localhost:8000/messages/4
Content-Type: application/json

{
  "user": "Stephy",
  "content": "Epoo clg varum?"
}

###

# DELETE a message by ID
DELETE http://localhost:8000/messages/2
